source entities/create_partitioning_entities.sql
source routines/create_daily_partitions.sql
source routines/create_monthly_partitions.sql
source routines/create_weekly_partitions.sql
source routines/create_yearly_partitions.sql
source routines/manage_partitions.sql
